linters-settings:
  errcheck:
    ignore: "fmt:.*,github.com/kpango/glg:.*"
issues:
  max-same-issues: 0
  # exclude:
  #   - Error return value of .(glg.(Info|Log|Debug|Warn|Error|Success|Fail|Print|Println|CustomLog)f?). is not checked
linters:
  presets:
    # - bugs
    - comment
    # - complexity
    # - error
    # - format
    # - import
    # - metalinter
    - module
    - performance
    # - sql
    # - style
    # - test
    - unused
  disable:
    - varcheck
    - deadcode
    - structcheck
    - maligned
    - dupword
    - godox
